openapi: 3.0.1
info:
  title: Flight Booking System
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /api/v1/flights:
    get:
      summary: Получить список рейстов
      tags:
        - Gateway API
      responses:
        "200":
          description: Список рейсов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FlightResponse"

  /api/v1/tickets:
    get:
      summary: Информация по всем билетам пользователя
      tags:
        - Gateway API
      parameters:
        - name: X-User-Name
          in: header
          description: Имя пользователя
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Информация по всем билетам
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TicketResponse"

    post:
      summary: Покупка билета
      tags:
        - Gateway API
      parameters:
        - name: X-User-Name
          in: header
          description: Имя пользователя
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TicketPurchaseRequest"
      responses:
        "200":
          description: Информация о купленном билете
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TicketPurchaseResponse"
        "400":
          description: Ошибка валидации данных
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationErrorResponse"

  "/api/v1/tickets/{ticketUid}":
    get:
      summary: Информация по конкретному билету
      tags:
        - Gateway API
      parameters:
        - name: ticketUid
          schema:
            type: string
            format: uuid
          in: path
          description: UUID билета
          required: true
        - name: X-User-Name
          in: header
          description: Имя пользователя
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Информация по конкретному билету
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TicketResponse"
        "404":
          description: Билет не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    delete:
      summary: Возврат билета
      tags:
        - Gateway API
      parameters:
        - name: ticketUid
          schema:
            type: string
            format: uuid
          in: path
          description: UUID билета
          required: true
        - name: X-User-Name
          in: header
          description: Имя пользователя
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Возврат билета успешно выполнен
        "404":
          description: Билет не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/me:
    get:
      summary: Информация о пользователе
      tags:
        - Gateway API
      parameters:
        - name: X-User-Name
          in: header
          description: Имя пользователя
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Польная информация о пользователе
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfoResponse"

  /api/v1/privilege:
    get:
      summary: Получить историю бонусного счета
      tags:
        - Gateway API
      parameters:
        - name: X-User-Name
          in: header
          description: Имя пользователя
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Данные о бонусном счете
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PrivilegeInfoResponse"

components:
  schemas:
    FlightResponse:
      type: object
      example:
        {
          flight_number: "AFL031",
          from_airport: "Санкт-Петербург Пулково",
          to_airport: "Москва Шереметьево",
          date: "2021-10-08T19:59:19Z",
          price: 1500
        }
      properties:
        flight_number:
          type: string
          description: Номер полета
        from_airport:
          type: string
          description: Страна и аэропорт прибытия
        to_airport:
          type: string
          description: Страна и аэропорт прибытия
        date:
          type: string
          description: Дата и время вылета
          format: ISO 8601
        price:
          type: number
          description: Стоимость

    TicketResponse:
      type: object
      example:
        {
          ticket_uid: "049161bb-badd-4fa8-9d90-87c9a82b0668",
          flight_number: "AFL031",
          from_airport: "Санкт-Петербург Пулково",
          to_airport: "Москва Шереметьево",
          date: "2021-10-08T19:59:19Z",
          price: 1500
        }
      properties:
        ticket_uid:
          type: string
          description: UUID билета
          format: uuid
        flight_number:
          type: string
          description: Номер полета
        from_airport:
          type: string
          description: Страна и аэропорт прибытия
        to_airport:
          type: string
          description: Страна и аэропорт прибытия
        date:
          type: string
          description: Дата и время вылета
          format: ISO 8601
        price:
          type: number
          description: Стоимость

    UserInfoResponse:
      type: object
      example:
        {
          tickets: [
            {
              ticket_uid: "049161bb-badd-4fa8-9d90-87c9a82b0668",
              flight_number: "AFL031",
              from_airport: "Санкт-Петербург Пулково",
              to_airport: "Москва Шереметьево",
              date: "2021-10-08T19:59:19Z",
              price: 1500
            }
          ],
          privilege: {
            balance: 1500,
            status: "GOLD"
          }
        }
      properties:
        tickets:
          type: array
          description: Информация о билетах пользоватлея
          items:
            $ref: "#/components/schemas/TicketResponse"
        privilege:
          $ref: "#/components/schemas/PrivilegeShortInfo"

    PrivilegeShortInfo:
      type: object
      properties:
        balance:
          type: string
          description: Баланс бонусного счета
        status:
          type: string
          description: Статус в бонусной программе
          enum:
            - BRONZE
            - SILVER
            - GOLD

    PrivilegeInfoResponse:
      type: object
      example:
        {
          balance: 1500,
          status: "GOLD",
          history: [
            {
              date: "2021-10-08T19:59:19Z",
              balance_diff: 1500,
              operation_type: "FILL_IN_BALANCE"
            }
          ]
        }
      properties:
        balance:
          type: string
          description: Баланс бонусного счета
        status:
          type: string
          description: Статус в бонусной программе
          enum:
            - BRONZE
            - SILVER
            - GOLD
        history:
          type: array
          description: История изменения баланса
          items:
            $ref: "#/components/schemas/BalanceHistory"

    BalanceHistory:
      type: object
      properties:
        date:
          type: string
          description: Дата и время операции
          format: ISO 8601
        balance_diff:
          type: string
          description: Изменение баланса
        operation_type:
          type: string
          description: Тип операции
          enum:
            - FILL_IN_BALANCE
            - DEBIT_THE_ACCOUNT
            - FILLED_BY_MONEY

    TicketPurchaseRequest:
      type: object
      example:
        {
          flight_number: "AFL031",
          date: "2021-10-08T19:59:19Z",
          price: 1500,
          paid_from_balance: true
        }
      properties:
        flight_number:
          type: string
          description: Номер полета
        date:
          type: string
          description: Дата и время вылета
          format: ISO 8601
        price:
          type: number
          description: Стоимость
        paid_from_balance:
          type: boolean
          description: Выполнить списание бонусных баллов в учет покупки билета

    TicketPurchaseResponse:
      type: object
      example:
        {
          ticket_uid: "049161bb-badd-4fa8-9d90-87c9a82b0668",
          flight_number: "AFL031",
          from_airport: "Санкт-Петербург Пулково",
          to_airport: "Москва Шереметьево",
          date: "2021-10-08T19:59:19Z",
          price: 1500,
          paid_by_money: 1500,
          paid_by_bonuses: 0,
          privilege: {
            balance: 1500,
            status: "GOLD"
          }
        }
      properties:
        ticket_uid:
          type: string
          description: UUID билета
          format: uuid
        flight_number:
          type: string
          description: Номер полета
        from_airport:
          type: string
          description: Страна и аэропорт прибытия
        to_airport:
          type: string
          description: Страна и аэропорт прибытия
        date:
          type: string
          description: Время вылета 
          format: ISO 8601
        price:
          type: number
          description: Стоимость
        paid_by_money:
          type: number
          description: Сумма оплаченная деньгами
        paid_by_bonuses:
          type: number
          description: Сумма оплаченная бонусами
        privilege:
          $ref: "#/components/schemas/PrivilegeShortInfo"

    ErrorDescription:
      type: object
      properties:
        field:
          type: string
        error:
          type: string

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Информация об ошибке

    ValidationErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Информация об ошибке
        errors:
          type: array
          description: Массив полей с описанием ошибки
          items:
            $ref: "#/components/schemas/ErrorDescription"
